#! /bin/sh

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width        	2.5
bspc config window_gap              25
bspc config right_padding	    0
bspc config left_padding	    0
bspc config top_padding		    0
bspc config bottom_padding	    0

bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config paddingless_monocle		true
bspc config focus_follows_pointer	false
bspc config normal_border_color '#0f0f0f'
bspc config focused_border_color '#ffffff'
bspc config click_to_focus true

bspc rule -a Wine floating=on
bspc rule -a exefile floating=on
bspc rule -a Firefox  desktop='^2'
bspc rule -a CodeBlocks dekstop='^3'
bspc rule -a Steam state=floating desktop='^5'
bspc rule -a mpv state=floating desktop='^6'
bspc rule -a PlayOnLinux desktop='^7'
bspc rule -a VirtualBox desktop='^7'
