#! /bin/sh
exec /home/ebc/.scripts/rnwal.sh & 
exec /home/ebc/.scripts/dnotif.sh &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width        	1.75
bspc config window_gap              35
bspc config right_padding	    0
bspc config left_padding	    0

bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_follows_pointer	false
bspc config focus_by_distance		true
bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'

bspc config super mod4
bspc config click_to_focus true

bspc rule -a CodeBlocks dekstop='^3'
bspc rule -a Firefox  desktop='^2'
bspc rule -a mpv state=floating desktop='^6'
bspc rule -a Steam state=floating desktop='^5'
bspc rule -a PlayOnLinux desktop='^7'
bspc rule -a VirtualBox desktop='^7'
bspc rule -a urxvt state=floating
